import json

notebook_path = r"C:\Users\yeonj\OneDrive\바탕 화면\DeepLearning_code\PINN\Dipol.ipynb"

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# PINN(Physics-Informed Neural Networks)을 활용한 2차원 원형 다이폴 안테나 전자기장 해석\n",
            "\n",
            "이 노트북에서는 안테나의 가장 기본적인 형태인 **다이폴 안테나(Dipole Antenna)**의 2차원 단면에서의 전위 및 전기장 분포를 물리 정보 신경망(PINN)을 사용해 해석합니다.  \n",
            "\n",
            "이전의 패치 안테나 모델은 매우 얇은 선 형태의 특이점(Singularity) 때문에 수렴이 어려웠던 반면, **원형 다이폴 안테나**는 도체를 2차원 원형 디스크(Circular Disk) 형태로 정의하여 특이점을 없앴습니다.  \n",
            "덕분에 사전 학습(Pre-training)이나 L-BFGS, 복잡한 손실 함수 가중치 튜닝 같은 복잡한 기교 없이, **가장 표준적인 Adam 옵티마이저와 기본적인 PINN 설정만으로도 매우 쉽게 학습에 성공**할 수 있습니다.\n",
            "\n",
            "## 1. 물리적 모델링 및 경계 조건 (Boundary Conditions)\n",
            "\n",
            "*   **양극 도체 (Positive Pole)**: 중심 $(0.0, 0.4)$, 반경 $0.2$ 인 원형 내부 및 표면 ➔ 전위 $V = +1.0$ (빨간색)\n",
            "*   **음극 도체 (Negative Pole)**: 중심 $(0.0, -0.4)$, 반경 $0.2$ 인 원형 내부 및 표면 ➔ 전위 $V = -1.0$ (파란색)\n",
            "*   **외부 가상 경계 (Outer Boundary)**: 영역 외곽선 ($x = \\pm 1.0, y = \\pm 1.0$) ➔ 전위 $V = 0.0$ (검은색)\n",
            "*   **자유 공간 (Free Space)**: 두 도체 원을 제외한 나머지 영역 ➔ 라플라스 방정식 $\\nabla^2 V = 0$ 만족"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import torch\n",
            "import torch.nn as nn\n",
            "import torch.optim as optim\n",
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "import time\n",
            "\n",
            "# 재현성을 위한 난수 시드 고정\n",
            "torch.manual_seed(42)\n",
            "np.random.seed(42)\n",
            "\n",
            "# ==========================================\n",
            "# 1. 도메인 및 배치 포인트 생성\n",
            "# ==========================================\n",
            "\n",
            "N_u = 600   # 경계 및 도체 내부 포인트 개수\n",
            "N_f = 2000  # 자유 공간 내부 물리 법칙(PDE) 적용 포인트 개수\n",
            "\n",
            "# 1-1. 양극 도체 포인트 생성 (V = +1.0)\n",
            "r_p = np.sqrt(np.random.uniform(0, 0.2**2, (200, 1)))\n",
            "theta_p = np.random.uniform(0, 2*np.pi, (200, 1))\n",
            "x_pos = r_p * np.cos(theta_p)\n",
            "y_pos = 0.4 + r_p * np.sin(theta_p)\n",
            "V_pos = np.ones_like(x_pos) * 1.0\n",
            "X_pos = np.hstack((x_pos, y_pos))\n",
            "\n",
            "# 1-2. 음극 도체 포인트 생성 (V = -1.0)\n",
            "r_n = np.sqrt(np.random.uniform(0, 0.2**2, (200, 1)))\n",
            "theta_n = np.random.uniform(0, 2*np.pi, (200, 1))\n",
            "x_neg = r_n * np.cos(theta_n)\n",
            "y_neg = -0.4 + r_n * np.sin(theta_n)\n",
            "V_neg = np.ones_like(x_neg) * -1.0\n",
            "X_neg = np.hstack((x_neg, y_neg))\n",
            "\n",
            "# 1-3. 외곽 경계 포인트 생성 (V = 0.0)\n",
            "x_l = -np.ones((50, 1))\n",
            "y_l = np.random.uniform(-1.0, 1.0, (50, 1))\n",
            "x_r = np.ones((50, 1))\n",
            "y_r = np.random.uniform(-1.0, 1.0, (50, 1))\n",
            "y_b = -np.ones((50, 1))\n",
            "x_b = np.random.uniform(-1.0, 1.0, (50, 1))\n",
            "y_t = np.ones((50, 1))\n",
            "x_t = np.random.uniform(-1.0, 1.0, (50, 1))\n",
            "\n",
            "X_outer = np.vstack((np.hstack((x_l, y_l)), np.hstack((x_r, y_r)), np.hstack((x_b, y_b)), np.hstack((x_t, y_t))))\n",
            "V_outer = np.zeros((X_outer.shape[0], 1))\n",
            "\n",
            "# 경계 및 소스 데이터를 하나로 합칩니다\n",
            "X_u = torch.FloatTensor(np.vstack((X_pos, X_neg, X_outer)))\n",
            "V_u = torch.FloatTensor(np.vstack((V_pos, V_neg, V_outer)))\n",
            "\n",
            "# 1-4. 자유 공간 내부 물리 검증점 생성 (도체 내부 제외)\n",
            "x_f = np.random.uniform(-1.0, 1.0, (N_f * 3, 1))\n",
            "y_f = np.random.uniform(-1.0, 1.0, (N_f * 3, 1))\n",
            "X_f_np = np.hstack((x_f, y_f))\n",
            "\n",
            "dist_pos = np.sqrt(X_f_np[:, 0]**2 + (X_f_np[:, 1] - 0.4)**2)\n",
            "dist_neg = np.sqrt(X_f_np[:, 0]**2 + (X_f_np[:, 1] + 0.4)**2)\n",
            "mask = (dist_pos > 0.2) & (dist_neg > 0.2)\n",
            "X_f_np = X_f_np[mask][:N_f]\n",
            "\n",
            "X_f = torch.FloatTensor(X_f_np)\n",
            "X_f.requires_grad_(True)  # 편미분 계산용\n",
            "\n",
            "# 도메인 가시화\n",
            "plt.figure(figsize=(6, 6))\n",
            "plt.scatter(X_f[:, 0].detach().numpy(), X_f[:, 1].detach().numpy(), c='lightgray', s=5, label='Free Space (PDE)')\n",
            "plt.scatter(X_pos[:, 0], X_pos[:, 1], c='red', s=10, label='Positive Pole (V = +1.0)')\n",
            "plt.scatter(X_neg[:, 0], X_neg[:, 1], c='blue', s=10, label='Negative Pole (V = -1.0)')\n",
            "plt.scatter(X_outer[:, 0], X_outer[:, 1], c='black', s=10, label='Outer Boundary (V = 0.0)')\n",
            "plt.title('Collocation Points (Dipole Antenna)')\n",
            "plt.xlabel('x')\n",
            "plt.ylabel('y')\n",
            "plt.legend(loc='upper right')\n",
            "plt.grid(True, alpha=0.3)\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. 하이퍼파라미터 및 신경망 구조 설정\n",
            "\n",
            "다층 퍼셉트론(MLP)은 부드러운 전위의 미분을 표현할 수 있는 하이퍼볼릭 탄젠트(`Tanh`) 활성화 함수를 사용합니다.  \n",
            "입력은 2차원 공간 좌표 $(x, y)$이고, 출력은 해당 위치의 전위 $V(x, y)$입니다."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "learning_rate = 1e-3\n",
            "epochs = 2000\n",
            "hidden_layers = [64, 64, 64]\n",
            "\n",
            "class TanhLayer(nn.Module):\n",
            "    def __init__(self, in_features, out_features):\n",
            "        super(TanhLayer, self).__init__()\n",
            "        self.linear = nn.Linear(in_features, out_features)\n",
            "    def forward(self, x):\n",
            "        return torch.tanh(self.linear(x))\n",
            "\n",
            "class DynamicTanhPINN(nn.Module):\n",
            "    def __init__(self, input_size, hidden_layers, output_size):\n",
            "        super(DynamicTanhPINN, self).__init__()\n",
            "        self.layers = nn.ModuleList()\n",
            "        self.layers.append(TanhLayer(input_size, hidden_layers[0]))\n",
            "        for i in range(len(hidden_layers)-1):\n",
            "            self.layers.append(TanhLayer(hidden_layers[i], hidden_layers[i+1]))\n",
            "        self.output_layer = nn.Linear(hidden_layers[-1], output_size)\n",
            "        \n",
            "    def forward(self, x):\n",
            "        out = x\n",
            "        for layer in self.layers:\n",
            "            out = layer(out)\n",
            "        out = self.output_layer(out)\n",
            "        return out, None\n",
            "\n",
            "model = DynamicTanhPINN(input_size=2, hidden_layers=hidden_layers, output_size=1)\n",
            "print(model)"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. 물리 법칙 손실 함수 (PDE Loss) 정의\n",
            "\n",
            "자유 공간 내부($X_f$)에서는 정전기학의 기본 물리 법칙인 **라플라스 방정식**이 성립해야 합니다.\n",
            "$$\\nabla^2 V = \\frac{\\partial^2 V}{\\partial x^2} + \\frac{\\partial^2 V}{\\partial y^2} = 0$$\n",
            "\n",
            "PyTorch의 자동 미분(`torch.autograd.grad`)을 이용해 2차 공간 미분값을 계산해 줍니다."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def calc_pde_loss(model_net, x_points):\n",
            "    pred, _ = model_net(x_points)\n",
            "    # 1. 1차 미분 (dV/dx, dV/dy)\n",
            "    grad_V = torch.autograd.grad(pred, x_points, grad_outputs=torch.ones_like(pred), create_graph=True)[0]\n",
            "    dV_dx = grad_V[:, 0:1]\n",
            "    dV_dy = grad_V[:, 1:2]\n",
            "    \n",
            "    # 2. 2차 미분 (d2V/dx2, d2V/dy2)\n",
            "    grad_dV_dx = torch.autograd.grad(dV_dx, x_points, grad_outputs=torch.ones_like(dV_dx), create_graph=True)[0]\n",
            "    d2V_dx2 = grad_dV_dx[:, 0:1]\n",
            "    \n",
            "    grad_dV_dy = torch.autograd.grad(dV_dy, x_points, grad_outputs=torch.ones_like(dV_dy), create_graph=True)[0]\n",
            "    d2V_dy2 = grad_dV_dy[:, 1:2]\n",
            "    \n",
            "    # 라플라시안 계산\n",
            "    laplacian = d2V_dx2 + d2V_dy2\n",
            "    loss_pde = torch.mean(laplacian**2)\n",
            "    return loss_pde"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. PINN 반복 학습 수행\n",
            "\n",
            "가장 기본적인 Adam 옵티마이저를 사용해 2000 에포크 동안 학습합니다.  \n",
            "전체 손실 함수는 **경계 조건(BC) 손실과 물리 법칙(PDE) 손실의 선형 결합**으로 정의되며, 가중치는 표준적인 `100.0`을 사용합니다.\n",
            "$$\\text{Total Loss} = 100.0 \\times \\text{Loss_BC} + \\text{Loss_PDE}$$"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "optimizer = optim.Adam(model.parameters(), lr=learning_rate)\n",
            "\n",
            "loss_history = []\n",
            "start_time = time.time()\n",
            "\n",
            "print(\"--- 다이폴 안테나 학습 시작 ---\")\n",
            "for epoch in range(epochs):\n",
            "    optimizer.zero_grad()\n",
            "    \n",
            "    # 1. 경계 조건 손실 계산 (Loss_BC)\n",
            "    u_pred_bc, _ = model(X_u)\n",
            "    Loss_BC = nn.MSELoss()(u_pred_bc, V_u)\n",
            "    \n",
            "    # 2. 물리 법칙 손실 계산 (Loss_PDE)\n",
            "    Loss_PDE = calc_pde_loss(model, X_f)\n",
            "    \n",
            "    # 3. 토탈 Loss 계산 및 역전파\n",
            "    loss = 100.0 * Loss_BC + Loss_PDE\n",
            "    loss.backward()\n",
            "    optimizer.step()\n",
            "    \n",
            "    loss_history.append(loss.item())\n",
            "    \n",
            "    if (epoch + 1) % 200 == 0 or epoch == 0:\n",
            "        print(f\"Epoch [{epoch+1:4d}/{epochs}], Total Loss: {loss.item():.6e} (BC: {Loss_BC.item():.6e}, PDE: {Loss_PDE.item():.6e})\")\n",
            "\n",
            "print(f\"학습 완료! (소요 시간: {time.time() - start_time:.2f}초)\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. 전위 및 전기장 시각화\n",
            "\n",
            "학습된 신경망으로부터 전위 분포 $V(x, y)$와 이로부터 전기장 $\\vec{E} = -\\nabla V$를 유도하여 시각화합니다."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 5-1. 그리드 데이터 생성\n",
            "x_grid = np.linspace(-1.0, 1.0, 100)\n",
            "y_grid = np.linspace(-1.0, 1.0, 100)\n",
            "X_mesh, Y_mesh = np.meshgrid(x_grid, y_grid)\n",
            "grid_tensor = torch.FloatTensor(np.c_[X_mesh.ravel(), Y_mesh.ravel()])\n",
            "grid_tensor.requires_grad = True\n",
            "\n",
            "# 5-2. 전위 및 전기장 계산\n",
            "V_pred, _ = model(grid_tensor)\n",
            "grad_V = torch.autograd.grad(V_pred, grid_tensor, grad_outputs=torch.ones_like(V_pred), create_graph=False)[0]\n",
            "\n",
            "Ex = -grad_V[:, 0:1].detach().numpy().reshape(X_mesh.shape)\n",
            "Ey = -grad_V[:, 1:2].detach().numpy().reshape(X_mesh.shape)\n",
            "E_magnitude = np.sqrt(Ex**2 + Ey**2)\n",
            "V_pred_np = V_pred.detach().numpy().reshape(X_mesh.shape)\n",
            "\n",
            "# 시각화\n",
            "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))\n",
            "\n",
            "# 1. 전위 분포 히트맵\n",
            "contour_v = ax1.contourf(X_mesh, Y_mesh, V_pred_np, levels=50, cmap='viridis')\n",
            "fig.colorbar(contour_v, ax=ax1, label='Potential V (V)')\n",
            "# 도체 그리기\n",
            "circle_p = plt.Circle((0, 0.4), 0.2, color='red', fill=False, linewidth=2, label='Positive Pole')\n",
            "circle_n = plt.Circle((0, -0.4), 0.2, color='blue', fill=False, linewidth=2, label='Negative Pole')\n",
            "ax1.add_patch(circle_p)\n",
            "ax1.add_patch(circle_n)\n",
            "ax1.set_title(\"Predicted Potential V(x,y)\")\n",
            "ax1.set_xlabel(\"x\")\n",
            "ax1.set_ylabel(\"y\")\n",
            "ax1.legend(loc='upper right')\n",
            "\n",
            "# 2. 전기장 벡터 및 세기 분포\n",
            "contour_e = ax2.contourf(X_mesh, Y_mesh, E_magnitude, levels=50, cmap='plasma')\n",
            "fig.colorbar(contour_e, ax=ax2, label='E-field Magnitude (V/m)')\n",
            "sub = 5\n",
            "ax2.quiver(X_mesh[::sub, ::sub], Y_mesh[::sub, ::sub], \n",
            "           Ex[::sub, ::sub] / (E_magnitude[::sub, ::sub] + 1e-8), \n",
            "           Ey[::sub, ::sub] / (E_magnitude[::sub, ::sub] + 1e-8), \n",
            "           color='white', alpha=0.6, scale=25)\n",
            "circle_p_e = plt.Circle((0, 0.4), 0.2, color='red', fill=False, linewidth=2)\n",
            "circle_n_e = plt.Circle((0, -0.4), 0.2, color='blue', fill=False, linewidth=2)\n",
            "ax2.add_patch(circle_p_e)\n",
            "ax2.add_patch(circle_n_e)\n",
            "ax2.set_title(\"Electric Field Vectors & Magnitude\")\n",
            "ax2.set_xlabel(\"x\")\n",
            "ax2.set_ylabel(\"y\")\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    }
]

notebook_data = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.4"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_data, f, indent=1, ensure_ascii=False)

print("Created Dipol.ipynb successfully!")
