import json

path = r"C:\Users\yeonj\OneDrive\바탕 화면\DeepLearning_code\PINN\reflect.ipynb"
with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

new_source = [
    "# ==========================================\n",
    "# 7. 반복 학습 수행 및 결과 시각화 (전위)\n",
    "# ==========================================\n",
    "\n",
    "# 본격적인 학습을 위해 완전히 깨끗한 새 모델을 초기화한다\n",
    "model_final = DynamicTanhPINN(input_size=2, hidden_layers=hidden_layers, output_size=1)\n",
    "\n",
    "loss_history_final = []\n",
    "start_time = time.time()\n",
    "\n",
    "# 7-1. 1단계: 경계 조건(BC) 사전 학습 (Pre-training)\n",
    "# 물리 법칙을 입히기 전에 경계 조건을 먼저 뇌에 새겨줍니다.\n",
    "print(\"--- [1단계] 경계 조건 사전 학습 시작 (1000 에포크) ---\")\n",
    "optimizer_pre = optim.Adam(model_final.parameters(), lr=1e-3)\n",
    "for epoch in range(1000):\n",
    "    optimizer_pre.zero_grad()\n",
    "    u_pred_bc, _ = model_final(X_u)\n",
    "    Loss_BC = nn.MSELoss()(u_pred_bc, V_u)\n",
    "    Loss_BC.backward()\n",
    "    optimizer_pre.step()\n",
    "    if (epoch + 1) % 200 == 0:\n",
    "        print(f\"Epoch [{epoch+1:4d}/1000], BC Loss: {Loss_BC.item():.6e}\")\n",
    "\n",
    "# 7-2. 2단계: 물리 법칙(PDE)과 경계 조건의 결합 학습\n",
    "# 가중치를 높게 설정(10000.0)하여 경계 조건이 깨지지 않게 물리 법칙(라플라스 방정식)을 학습합니다.\n",
    "print(\"\\n--- [2단계] PINN 물리 법칙 결합 학습 시작 (2000 에포크) ---\")\n",
    "optimizer_final = optim.Adam(model_final.parameters(), lr=2e-4) # 안정적인 미세조정을 위해 러닝레이트 조정\n",
    "for epoch in range(epochs):\n",
    "    optimizer_final.zero_grad()\n",
    "    \n",
    "    # 1. 경계면 오차 계산 (Loss_BC)\n",
    "    u_pred_bc, _ = model_final(X_u)\n",
    "    Loss_BC = nn.MSELoss()(u_pred_bc, V_u)\n",
    "    \n",
    "    # 2. 자유 공간 내부의 물리 법칙 잔차 계산 (Loss_PDE)\n",
    "    Loss_PDE = calc_pde_loss(model_final, X_f)\n",
    "    \n",
    "    # 3. 토탈 Loss 역전파 및 최적화 (BC 가중치를 10000.0으로 강화)\n",
    "    loss = 10000.0 * Loss_BC + Loss_PDE\n",
    "    loss.backward()\n",
    "    optimizer_final.step()\n",
    "    \n",
    "    loss_history_final.append(loss.item())\n",
    "    \n",
    "    # 10% 진행될 때마다 학습 로그를 출력한다\n",
    "    if (epoch + 1) % (epochs // 10) == 0 or (epoch + 1) == 1:\n",
    "        print(f\"Epoch [{epoch+1:4d}/{epochs}], Total Loss: {loss.item():.6e} (Loss_BC: {Loss_BC.item():.6e}, Loss_PDE: {Loss_PDE.item():.6e})\")\n",
    "\n",
    "print(f\"\\n전위 학습 완료! (소요 시간: {time.time() - start_time:.2f}초)\")\n",
    "\n",
    "# 학습 경과 그래프와 전위 히트맵 시각화 패널\n",
    "fig = plt.figure(figsize=(15, 5))\n",
    "\n",
    "# 1. Loss 곡선 시각화\n",
    "ax1 = fig.add_subplot(1, 2, 1)\n",
    "ax1.plot(loss_history_final, color='blue', linewidth=2)\n",
    "ax1.set_yscale('log')\n",
    "ax1.set_title('Training Loss Curve')\n",
    "ax1.set_xlabel('Epochs')\n",
    "ax1.set_ylabel('Total PINN Loss')\n",
    "ax1.grid(True, linestyle='--', alpha=0.6)\n",
    "\n",
    "# 2. 예측된 전위 V(x,y) 히트맵\n",
    "ax2 = fig.add_subplot(1, 2, 2)\n",
    "x_grid = np.linspace(-1.0, 1.0, 100)\n",
    "y_grid = np.linspace(0.0, 1.0, 100)\n",
    "X_mesh, Y_mesh = np.meshgrid(x_grid, y_grid)\n",
    "grid_tensor = torch.FloatTensor(np.c_[X_mesh.ravel(), Y_mesh.ravel()])\n",
    "\n",
    "with torch.no_grad():\n",
    "    V_pred, _ = model_final(grid_tensor)\n",
    "V_pred = V_pred.numpy().reshape(X_mesh.shape)\n",
    "\n",
    "contour = ax2.contourf(X_mesh, Y_mesh, V_pred, levels=50, cmap='viridis')\n",
    "fig.colorbar(contour, ax=ax2, label='Potential (V)')\n",
    "ax2.set_title(\"Predicted Potential V(x,y)\")\n",
    "ax2.set_xlabel(\"x (m)\")\n",
    "ax2.set_ylabel(\"y (m)\")\n",
    "ax2.plot([-0.4, 0.4], [0.2, 0.2], 'r-', linewidth=4, label='Patch')\n",
    "ax2.plot([-1.0, 1.0], [0.0, 0.0], 'k-', linewidth=4, label='Ground')\n",
    "ax2.legend(loc='upper right')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]

nb["cells"][13]["source"] = new_source

with open(path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Successfully updated cell index 13 in the notebook!")
